
/*

MongoDB OjbectID

ObjectIDs are generated by the MongoDB driver, not MongoDB.

_id: 5d124d26b88cc36f11369811

- 24 characters
- every two characters represent a byte
- 12 bytes total

- first 4 bytes represent a timestamp
- next 3 bytes represent a machine identifier
- next 2 bytes represent a process identifier
- last 3 bytes represent a counter

- 1 byte = 8 bits

*/

const mongoose = require('mongoose');

// generate an ObjectID
const id = new mongoose.Types.ObjectId();
console.log('id', id);

//get timestamp
console.log('id.getTimestamp()', id.getTimestamp());

const isValid1 = mongoose.Types.ObjectId.isValid('1234');
const isValid2 = mongoose.Types.ObjectId.isValid(id);
console.log('isValid1', isValid1);
console.log('isValid2', isValid2);

